language: node_js
node_js:
  - 0.6
before_script:
  - cd ./test/server && npm install express && cd ../../ && 
  - sudo node ./test/server/app.js 80 && 
  - sleep 5
script: phantomjs test/phantomscript.js "http://localhost:80"